### ISSUE TITLE
xliff2po throws error

### ISSUE THREAD

**Issue by transl8bzimport** [translate/translate#2879]
_Version: trunk_

_Originally posted by Matt Kynaston:_

I'm seeing the following error with xliff2po from trunk and 1.10.0:

$ xliff2po default.xlf test.po
processing 1 files...
xliff2po: WARNING: Error processing: input default.xlf, output test.po, template None: convertxliff() got an unexpected keyword argument 'duplicatestyle'
[###########################################] 100%

The same command with the same file works with 1.9.0

Environment: OSX 10.8.3, (system) Python 2.7.

Please let me know if there is any other information that would help.
